{
 "title": "ECS监控",
 "tags": [
  "ECS",
  "阿里云"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "name", "label": "实例名称", "query": "ecs" },
   { "name": "id", "query": "ecs($name)" },
   {
    "name": "dimension",
    "label": "实例ID",
    "query": "dimension(acs_ecs_dashboard, CPUUtilization,$id,null),"
   },
   { "name": "ip", "label": "IP", "query": "ecs_ip($name)" }
  ]
 },
 "panels": [
  { "title": "概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "name" },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>$ip</span>\n</div>\n\n\n\n",
   "targets": [
    { "project": "acs_ecs_dashboard", "type": "timeserie", "xcol": "timestamp" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "memory_totalspace",
     "period": "15",
     "project": "acs_ecs_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "diskusage_total",
     "period": "15",
     "project": "acs_ecs_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "私网流入带宽",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "IntranetInRate",
     "period": "60",
     "project": "acs_ecs_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "系统磁盘总读BPS",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "DiskReadBPS",
     "period": "60",
     "project": "acs_ecs_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "系统磁盘读IOPS",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "format": "cps",
   "valueName": "current",
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "DiskReadIOPS",
     "period": "60",
     "project": "acs_ecs_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 3 },
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "cpu_total",
     "period": "15",
     "project": "acs_ecs_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 3 },
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "memory_usedutilization",
     "period": "15",
     "project": "acs_ecs_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 3 },
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "diskusage_utilization",
     "period": "15",
     "project": "acs_ecs_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "私网流出带宽",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "IntranetOutRate",
     "period": "60",
     "project": "acs_ecs_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "系统磁盘总写BPS",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 6 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "DiskWriteBPS",
     "period": "60",
     "project": "acs_ecs_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "系统磁盘写IOPS",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "format": "cps",
   "valueName": "current",
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "DiskWriteIOPS",
     "period": "60",
     "project": "acs_ecs_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  { "title": "基础资源", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }, "repeat": "name" },
  {
   "title": "CPU 使用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "cpu_user",
     "period": "15",
     "project": "acs_ecs_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "memory_usedutilization",
     "period": "15",
     "project": "acs_ecs_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "系统负载",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "describe": "load_1m",
     "dimensions": [ "$id" ],
     "metric": "load_1m",
     "period": "15",
     "project": "acs_ecs_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    },
    {
     "describe": "load_5m",
     "dimensions": [ "$id" ],
     "metric": "load_5m",
     "period": "15",
     "project": "acs_ecs_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    },
    {
     "describe": "load_15m",
     "dimensions": [ "$id" ],
     "metric": "load_15m",
     "period": "15",
     "project": "acs_ecs_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "磁盘",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "repeat": "name",
   "collapsed": true,
   "panels": [
    {
     "title": "磁盘使用率",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "diskusage_utilization",
       "period": "15",
       "project": "acs_ecs_dashboard",
       "target": [
        "Average",
        "Minimum",
        "Maximum"
       ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [
        "Average",
        "Minimum",
        "Maximum"
       ]
      }
     ]
    },
    {
     "title": "磁盘已用存储空间",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "diskusage_used",
       "period": "15",
       "project": "acs_ecs_dashboard",
       "target": [
        "Average",
        "Minimum",
        "Maximum"
       ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [
        "Average",
        "Minimum",
        "Maximum"
       ]
      }
     ]
    },
    {
     "title": "系统磁盘总写BPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "DiskWriteBPS",
       "period": "60",
       "project": "acs_ecs_dashboard",
       "target": [
        "Average",
        "Minimum",
        "Maximum"
       ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [
        "Average",
        "Minimum",
        "Maximum"
       ]
      }
     ]
    },
    {
     "title": "系统磁盘总读BPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "DiskReadBPS",
       "period": "60",
       "project": "acs_ecs_dashboard",
       "target": [
        "Average",
        "Minimum",
        "Maximum"
       ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [
        "Average",
        "Minimum",
        "Maximum"
       ]
      }
     ]
    },
    {
     "title": "系统磁盘读IOPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "DiskReadIOPS",
       "period": "60",
       "project": "acs_ecs_dashboard",
       "target": [
        "Average",
        "Minimum",
        "Maximum"
       ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [
        "Average",
        "Minimum",
        "Maximum"
       ]
      }
     ]
    },
    {
     "title": "系统磁盘写IOPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "DiskWriteIOPS",
       "period": "60",
       "project": "acs_ecs_dashboard",
       "target": [
        "Average",
        "Minimum",
        "Maximum"
       ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [
        "Average",
        "Minimum",
        "Maximum"
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "网络",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "repeat": "name",
   "collapsed": true,
   "panels": [
    {
     "title": "私网流入带宽",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "IntranetInRate",
       "period": "60",
       "project": "acs_ecs_dashboard",
       "target": [
        "Average",
        "Minimum",
        "Maximum"
       ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [
        "Average",
        "Minimum",
        "Maximum"
       ]
      }
     ]
    },
    {
     "title": "私网流出带宽",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "IntranetOutRate",
       "period": "60",
       "project": "acs_ecs_dashboard",
       "target": [
        "Average",
        "Minimum",
        "Maximum"
       ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [
        "Average",
        "Minimum",
        "Maximum"
       ]
      }
     ]
    },
    {
     "title": "网卡的上行带宽",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "networkin_rate",
       "period": "900",
       "project": "acs_ecs_dashboard",
       "target": [
        "Average",
        "Minimum",
        "Maximum"
       ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [
        "Average",
        "Minimum",
        "Maximum"
       ]
      }
     ]
    },
    {
     "title": "网卡的下行带宽",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "networkout_rate",
       "period": "900",
       "project": "acs_ecs_dashboard",
       "target": [
        "Average",
        "Minimum",
        "Maximum"
       ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [
        "Average",
        "Minimum",
        "Maximum"
       ]
      }
     ]
    },
    {
     "title": "网卡每秒接收的数据包数",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "networkin_packages",
       "period": "900",
       "project": "acs_ecs_dashboard",
       "target": [
        "Average",
        "Minimum",
        "Maximum"
       ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [
        "Average",
        "Minimum",
        "Maximum"
       ]
      }
     ]
    },
    {
     "title": "网卡每秒发送的数据包数",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "networkout_packages",
       "period": "900",
       "project": "acs_ecs_dashboard",
       "target": [
        "Average",
        "Minimum",
        "Maximum"
       ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [
        "Average",
        "Minimum",
        "Maximum"
       ]
      }
     ]
    },
    {
     "title": "设备驱动器检测到的接收错误包的数量",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "networkin_errorpackages",
       "period": "900",
       "project": "acs_ecs_dashboard",
       "target": [
        "Average",
        "Minimum",
        "Maximum"
       ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [
        "Average",
        "Minimum",
        "Maximum"
       ]
      }
     ]
    },
    {
     "title": "设备驱动器检测到的发送错误包的数量",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "networkout_errorpackages",
       "period": "900",
       "project": "acs_ecs_dashboard",
       "target": [
        "Average",
        "Minimum",
        "Maximum"
       ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [
        "Average",
        "Minimum",
        "Maximum"
       ]
      }
     ]
    },
    {
     "title": "TCP连接数",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "net_tcpconnection",
       "period": "60",
       "project": "acs_ecs_dashboard",
       "target": [
        "Average",
        "Minimum",
        "Maximum"
       ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [
        "Average",
        "Minimum",
        "Maximum"
       ]
      }
     ]
    }
   ]
  }
 ]
}