{
 "title": "弹性公网IP",
 "tags": [
  "EIP",
  "阿里云"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "name", "label": "实例名称", "query": "eip" },
   { "name": "id", "query": "eip($name)" }
  ]
 },
 "panels": [
  {
   "title": "流出带宽",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "net_tx.rate",
     "period": "60",
     "project": "acs_vpc_eip",
     "target": [ "Value" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Value" ]
    }
   ]
  },
  {
   "title": "流入带宽",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "net_rx.rate",
     "period": "60",
     "project": "acs_vpc_eip",
     "target": [ "Value" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Value" ]
    }
   ]
  },
  {
   "title": "每秒流出数据包数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "net_txPkgs.rate",
     "period": "60",
     "project": "acs_vpc_eip",
     "target": [ "Value" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Value" ]
    }
   ]
  },
  {
   "title": "每秒流入数据包数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "net_rxPkgs.rate",
     "period": "60",
     "project": "acs_vpc_eip",
     "target": [ "Value" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Value" ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 16 },
   "content": "### [EIP 控制台](https://vpc.console.aliyun.com/eip/)"
  }
 ]
}