{
 "title": "MongoDB监控",
 "tags": [
  "MongoDB",
  "阿里云"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "name", "label": "实例名称", "query": "mongodb" },
   { "name": "id", "query": "mongodb($name)" },
   {
    "name": "method",
    "label": "操作",
    "query": "OpInsert, OpQuery, OpUpdate, OpDelete, OpGetmore, OpCommand"
   },
   { "name": "num", "label": "实例数", "query": "num(mongodb)" }
  ]
 },
 "panels": [
  { "title": "概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "name" },
  {
   "title": "CPU使用率",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "CPUUtilization",
     "period": "300",
     "project": "acs_mongodb",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "MemoryUtilization",
     "period": "300",
     "project": "acs_mongodb",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "DiskUtilization",
     "period": "300",
     "project": "acs_mongodb",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "IOPS使用率",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "IOPSUtilization",
     "period": "300",
     "project": "acs_mongodb",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "请求数",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "NumberRequests",
     "period": "300",
     "project": "acs_mongodb",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "平均每秒SQL查询数",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "QPS",
     "period": "300",
     "project": "acs_mongodb",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "连接数使用量",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "ConnectionAmount",
     "period": "300",
     "project": "acs_mongodb",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 7 },
   "content": "## [MongoDB 控制台](https://mongodb.console.aliyun.com/)",
   "targets": [
    { "project": "acs_ecs_dashboard", "type": "timeserie", "xcol": "timestamp" }
   ]
  },
  { "title": "趋势", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "name" },
  {
   "title": "平均每秒SQL查询数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "QPS",
     "period": "300",
     "project": "acs_mongodb",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "IOPS使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "IOPSUtilization",
     "period": "300",
     "project": "acs_mongodb",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "$method 操作次数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "$method",
     "period": "300",
     "project": "acs_mongodb",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "请求数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "NumberRequests",
     "period": "300",
     "project": "acs_mongodb",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  { "title": "资源", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }, "repeat": "name" },
  {
   "title": "CPU使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "CPUUtilization",
     "period": "300",
     "project": "acs_mongodb",
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "MemoryUtilization",
     "period": "300",
     "project": "acs_mongodb",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "网络入流量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "IntranetIn",
     "period": "300",
     "project": "acs_mongodb",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "网络出流量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "IntranetOut",
     "period": "300",
     "project": "acs_mongodb",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "DiskUtilization",
     "period": "300",
     "project": "acs_mongodb",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "数据占用磁盘空间量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "DataDiskAmount",
     "period": "300",
     "project": "acs_mongodb",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "实例占用磁盘空间量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "InstanceDiskAmount",
     "period": "300",
     "project": "acs_mongodb",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "日志占用磁盘空间量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "LogDiskAmount",
     "period": "300",
     "project": "acs_mongodb",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  }
 ]
}