{
 "title": "OSS监控",
 "tags": [
  "OSS",
  "阿里云"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dimension",
    "label": "Bucket名称",
    "query": "dimension(acs_oss_dashboard, Availability,null,null),"
   },
   {
    "name": "method",
    "label": "请求",
    "query": "GetObjectE2eLatency, GetObjectServerLatency, MaxGetObjectE2eLatency, MaxGetObjectServerLatency, HeadObjectE2eLatency, HeadObjectServerLatency, MaxHeadObjectE2eLatency,MaxHeadObjectServerLatency,PutObjectE2eLatency,PutObjectServerLatency,MaxPutObjectE2eLatency,MaxPutObjectServerLatency,PostObjectE2eLatency,PostObjectServerLatency,MaxPostObjectE2eLatency,MaxPostObjectServerLatency,AppendObjectE2eLatency,AppendObjectServerLatency,MaxAppendObjectE2eLatency,MaxAppendObjectServerLatency,UploadPartE2eLatency,UploadPartServerLatency,MaxUploadPartE2eLatency,MaxUploadPartServerLatency,UploadPartCopyE2eLatency,UploadPartCopyServerLatency,MaxUploadPartCopyE2eLatency,MaxUploadPartCopyServerLatency"
   },
   {
    "name": "success",
    "label": "成功请求方法",
    "query": "GetObjectCount,HeadObjectCount,PutObjectCount,PostObjectCount,AppendObjectCount,UploadPartCount,UploadPartCopyCount,DeleteObjectCount,DeleteObjectsCount"
   }
  ]
 },
 "panels": [
  { "title": "用户层级", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "用户层级有效请求率\t",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "metric": "UserRequestValidRate",
     "period": "60",
     "project": "acs_oss_dashboard",
     "target": [ "Value" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Value" ]
    }
   ]
  },
  {
   "title": "用户层级总请求数",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "metric": "UserTotalRequestCount",
     "period": "60",
     "project": "acs_oss_dashboard",
     "target": [ "Value" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Value" ]
    }
   ]
  },
  {
   "title": "用户层级有效请求数",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "metric": "UserValidRequestCount",
     "period": "60",
     "project": "acs_oss_dashboard",
     "target": [ "Value" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Value" ]
    }
   ]
  },
  {
   "title": "用户层级公网流出流量",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "metric": "UserInternetSend",
     "period": "60",
     "project": "acs_oss_dashboard",
     "target": [ "Value" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Value" ]
    }
   ]
  },
  {
   "title": "用户层级公网流入流量",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "metric": "UserInternetRecv",
     "period": "60",
     "project": "acs_oss_dashboard",
     "target": [ "Value" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Value" ]
    }
   ]
  },
  {
   "title": "用户层级内网流出流量",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "metric": "UserIntranetSend",
     "period": "60",
     "project": "acs_oss_dashboard",
     "target": [ "Value" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Value" ]
    }
   ]
  },
  {
   "title": "用户层级内网流入流量",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "metric": "UserIntranetRecv",
     "period": "60",
     "project": "acs_oss_dashboard",
     "target": [ "Value" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Value" ]
    }
   ]
  },
  {
   "title": "用户层级成功请求总数",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "metric": "UserSuccessCount",
     "period": "60",
     "project": "acs_oss_dashboard",
     "target": [ "Value" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Value" ]
    }
   ]
  },
  {
   "title": "用户层级成功请求总数",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "metric": "UserSuccessCount",
     "period": "60",
     "project": "acs_oss_dashboard",
     "target": [ "Value" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Value" ]
    }
   ]
  },
  {
   "title": "用户层级服务端错误请求总数",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "metric": "UserServerErrorCount",
     "period": "60",
     "project": "acs_oss_dashboard",
     "target": [ "Value" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Value" ]
    }
   ]
  },
  {
   "title": "用户层级服务端错误请求占比",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "metric": "UserServerErrorRate",
     "period": "60",
     "project": "acs_oss_dashboard",
     "target": [ "Value" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Value" ]
    }
   ]
  },
  {
   "title": "用户层级网络错误请求总数",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "metric": "UserNetworkErrorCount",
     "period": "60",
     "project": "acs_oss_dashboard",
     "target": [ "Value" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Value" ]
    }
   ]
  },
  {
   "title": "用户层级网络错误请求占",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "metric": "UserNetworkErrorRate",
     "period": "60",
     "project": "acs_oss_dashboard",
     "target": [ "Value" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Value" ]
    }
   ]
  },
  {
   "title": "Bucket层级",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "可用性",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "Availability",
       "period": "60",
       "project": "acs_oss_dashboard",
       "target": [ "Value" ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [ "Value" ]
      }
     ]
    },
    {
     "title": "有效请求率",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 2 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "RequestValidRate",
       "period": "60",
       "project": "acs_oss_dashboard",
       "target": [ "Value" ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [ "Value" ]
      }
     ]
    },
    {
     "title": "内网流出流量",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 2 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "IntranetSend",
       "period": "60",
       "project": "acs_oss_dashboard",
       "target": [ "Value" ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [ "Value" ]
      }
     ]
    },
    {
     "title": "内网流入流量",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 2 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "IntranetRecv",
       "period": "60",
       "project": "acs_oss_dashboard",
       "target": [ "Value" ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [ "Value" ]
      }
     ]
    },
    {
     "title": "公网流出流量",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 2 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "InternetSend",
       "period": "60",
       "project": "acs_oss_dashboard",
       "target": [ "Value" ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [ "Value" ]
      }
     ]
    },
    {
     "title": "公网流入流量",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 2 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "InternetRecv",
       "period": "60",
       "project": "acs_oss_dashboard",
       "target": [ "Value" ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [ "Value" ]
      }
     ]
    },
    {
     "title": "总请求数",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "TotalRequestCount",
       "period": "60",
       "project": "acs_oss_dashboard",
       "target": [ "Value" ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [ "Value" ]
      }
     ]
    },
    {
     "title": "有效请求数",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "ValidRequestCount",
       "period": "60",
       "project": "acs_oss_dashboard",
       "target": [ "Value" ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [ "Value" ]
      }
     ]
    },
    {
     "title": "服务端错误请求总数",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "ServerErrorCount",
       "period": "60",
       "project": "acs_oss_dashboard",
       "target": [ "Value" ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [ "Value" ]
      }
     ]
    },
    {
     "title": "服务端错误请求占比",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 7 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "ServerErrorRate",
       "period": "60",
       "project": "acs_oss_dashboard",
       "target": [ "Value" ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [ "Value" ]
      }
     ]
    },
    {
     "title": "网络错误请求总数",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "NetworkErrorCount",
       "period": "60",
       "project": "acs_oss_dashboard",
       "target": [ "Value" ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [ "Value" ]
      }
     ]
    },
    {
     "title": "网络错误请求占比",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 7 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "NetworkErrorRate",
       "period": "60",
       "project": "acs_oss_dashboard",
       "target": [ "Value" ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [ "Value" ]
      }
     ]
    },
    {
     "title": "客户端资源不存在错误请求总数",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "ResourceNotFoundErrorCount",
       "period": "60",
       "project": "acs_oss_dashboard",
       "target": [ "Value" ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [ "Value" ]
      }
     ]
    },
    {
     "title": "客户端资源不存在错误请求占比",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 12 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "ResourceNotFoundErrorRate",
       "period": "60",
       "project": "acs_oss_dashboard",
       "target": [ "Value" ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [ "Value" ]
      }
     ]
    },
    {
     "title": "客户端超时错误请求总数",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "ClientTimeoutErrorCount",
       "period": "60",
       "project": "acs_oss_dashboard",
       "target": [ "Value" ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [ "Value" ]
      }
     ]
    },
    {
     "title": "客户端超时错误请求占比",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 12 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "ClientTimeoutErrorRate",
       "period": "60",
       "project": "acs_oss_dashboard",
       "target": [ "Value" ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [ "Value" ]
      }
     ]
    },
    {
     "title": "成功请求总数",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "SuccessCount",
       "period": "60",
       "project": "acs_oss_dashboard",
       "target": [ "Value" ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [ "Value" ]
      }
     ]
    },
    {
     "title": "成功请求占比",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 12 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "SuccessRate",
       "period": "60",
       "project": "acs_oss_dashboard",
       "target": [ "Value" ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [ "Value" ]
      }
     ]
    },
    {
     "title": "$method 请求平均延时",
     "type": "graph",
     "description": "参数详情查看 https://help.aliyun.com/document_detail/31879.html",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "metric": "$method",
       "period": "60",
       "project": "acs_oss_dashboard",
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [ "Value" ]
      }
     ]
    },
    {
     "title": "$success 成功请求数",
     "type": "graph",
     "description": "参数详情查看 https://help.aliyun.com/document_detail/31879.html",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "metric": "$success",
       "period": "60",
       "project": "acs_oss_dashboard",
       "target": [ "Value" ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [ "Value" ]
      }
     ]
    }
   ]
  }
 ]
}