{
 "title": "Redis 监控",
 "tags": [
  "redis",
  "阿里云"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "name", "label": "实例名称", "query": "redis" },
   { "name": "id", "query": "redis($name)" },
   {
    "name": "cmd",
    "label": "命令",
    "query": "Standardappend,Standardbitcount,Standardbitop,Standardblpop,Standardbrpop,Standardbrpoplpush,Standarddecr,Standarddecrby,Standarddel,Standarddiscard,Standarddump,Standardexec,Standardexists,Standardexpire,Standardexpireat,StandardFailedCount,Standardget,Standardgetbit,Standardgetrange,Standardgetset,Standardhdel,Standardhexists,Standardhget,Standardhgetall,Standardhincrby,Standardhincrbyfloat,Standardhkeys,Standardhlen,Standardhmget,Standardhmset,Standardhscan,Standardhset,Standardhsetnx,Standardhvals,Standardincr,Standardincrby,Standardincrbyfloat,Standardlindex,Standardlinsert,Standardllen,Standardlpop,Standardlpush,Standardlpushx,Standardlrange,Standardlrem,Standardlset,Standardltrim,Standardmget,Standardmove,Standardmset,Standardmsetnx,Standardmulti,Standardpersist,Standardpexpire,Standardpexpireat,Standardpfadd,Standardpfcount,Standardpfmerge,Standardpsetex,Standardpsubscribe,Standardpttl,Standardpublish,Standardpubsub,Standardpunsubscribe,Standardrandomkey,Standardrename,Standardrenamenx,Standardrestore,Standardrpop,Standardrpoplpush,Standardrpush,Standardrpushx,Standardsadd,Standardscan,Standardscard,Standardsdiff,Standardsdiffstore,Standardset,Standardsetbit,Standardsetex,Standardsetnx,Standardsetrange,Standardsinter,Standardsinterstore,Standardsismember,Standardsmembers,Standardsmove,Standardsort,Standardspop,Standardsrandmember,Standardsrem,Standardsscan,Standardstrlen,Standardsubscribe,Standardsunion,Standardsunionstore,Standardttl,Standardtype,Standardunsubscribe,Standardunwatch,Standardwatch,Standardzadd,Standardzcard,Standardzcount,Standardzincrby,Standardzinterstore,Standardzlexcount,Standardzrange,Standardzrangebylex,Standardzrangebyscore,Standardzrank,Standardzrem,Standardzremrangebylex,Standardzremrangebyrank,Standardzremrangebyscore,Standardzrevrange,Standardzrevrangebyscore,Standardzrevrank,Standardzscan,Standardzscore,Standardzunionstore"
   }
  ]
 },
 "panels": [
  { "title": "概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "name" },
  {
   "title": "CPU使用率",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "StandardCpuUsage",
     "period": "60",
     "project": "acs_kvstore",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "StandardMemoryUsage",
     "period": "60",
     "project": "acs_kvstore",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "QPS使用率",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "StandardQPSUsage",
     "period": "60",
     "project": "acs_kvstore",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "流出带宽使用率",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "StandardIntranetOutRatio",
     "period": "60",
     "project": "acs_kvstore",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "流出带宽使用率",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "StandardIntranetOutRatio",
     "period": "60",
     "project": "acs_kvstore",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "µs",
   "valueName": "current",
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "StandardAvgRt",
     "period": "60",
     "project": "acs_kvstore",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "StandardKeys",
     "period": "60",
     "project": "acs_kvstore",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 9 },
   "content": "### [Redis 控制台](https://kvstorenext.console.aliyun.com/)"
  },
  { "title": "趋势", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }, "repeat": "name" },
  {
   "title": "CPU使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "StandardCpuUsage",
     "period": "60",
     "project": "acs_kvstore",
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "StandardMemoryUsage",
     "period": "60",
     "project": "acs_kvstore",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "$cmd 命令的执行频率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "$cmd",
     "period": "60",
     "project": "acs_kvstore",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "缓存内Key数量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "StandardKeys",
     "period": "60",
     "project": "acs_kvstore",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "连接数使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "StandardConnectionUsage",
     "period": "60",
     "project": "acs_kvstore",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "StandardAvgRt",
     "period": "60",
     "project": "acs_kvstore",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "流入带宽使用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "StandardIntranetInRatio",
     "period": "60",
     "project": "acs_kvstore",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "流出带宽使用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "StandardIntranetOutRatio",
     "period": "60",
     "project": "acs_kvstore",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  }
 ]
}