{
 "title": "SLB 监控",
 "tags": [
  "SLB",
  "阿里云"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "name", "label": "实例名称", "query": "slb" },
   { "name": "id", "query": "slb($name)" }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "dimension" },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>4层</span>\n</div>",
   "targets": [
    { "project": "acs_ecs_dashboard", "type": "timeserie", "xcol": "timestamp" }
   ]
  },
  {
   "title": "后端健康ECS实例个数",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "HeathyServerCount",
     "period": "60",
     "project": "acs_slb_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "后端异常ECS实例个数",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "UnhealthyServerCount",
     "period": "60",
     "project": "acs_slb_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "实例每秒活跃连接数",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "InstanceActiveConnection",
     "period": "60",
     "project": "acs_slb_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "实例每秒丢失连接数",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "InstanceDropConnection",
     "period": "60",
     "project": "acs_slb_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "实例每秒入bit数",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 3 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "InstanceTrafficRX",
     "period": "60",
     "project": "acs_slb_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "实例每秒出bit数",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 3 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "InstanceTrafficTX",
     "period": "60",
     "project": "acs_slb_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "新建连接数使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "InstanceNewConnectionUtilization",
     "period": "60",
     "project": "acs_slb_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "最大连接数使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "InstanceMaxConnectionUtilization",
     "period": "60",
     "project": "acs_slb_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "实例每秒活跃连接数\t",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "InstanceActiveConnection",
     "period": "60",
     "project": "acs_slb_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "实例每秒丢失连接数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "InstanceDropConnection",
     "period": "60",
     "project": "acs_slb_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "实例每秒丢失入包数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "InstanceDropPacketRX",
     "period": "60",
     "project": "acs_slb_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "实例每秒丢失出包数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "InstanceDropPacketTX",
     "period": "60",
     "project": "acs_slb_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "实例每秒非活跃连接数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "InstanceInactiveConnection",
     "period": "60",
     "project": "acs_slb_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "实例每秒最大并发连接数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "InstanceMaxConnection",
     "period": "60",
     "project": "acs_slb_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "实例每秒入包数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "InstancePacketRX",
     "period": "60",
     "project": "acs_slb_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "实例每秒出包数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "InstancePacketTX",
     "period": "60",
     "project": "acs_slb_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "实例每秒新建连接数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "InstanceNewConnection",
     "period": "60",
     "project": "acs_slb_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "repeat": "dimension",
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2 },
     "content": "<div class=\"text-center dashboard-header\">\n  <span>7层</span>\n</div>",
     "targets": [
      { "project": "acs_ecs_dashboard", "type": "timeserie", "xcol": "timestamp" }
     ]
    },
    {
     "title": "实例维度2xx状态码",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
     "format": "cps",
     "valueName": "current",
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "InstanceStatusCode2xx",
       "period": "60",
       "project": "acs_slb_dashboard",
       "target": [ "Average" ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [ "Average" ]
      }
     ]
    },
    {
     "title": "实例维度3xx状态码",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 4 },
     "format": "cps",
     "valueName": "current",
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "InstanceStatusCode3xx",
       "period": "60",
       "project": "acs_slb_dashboard",
       "target": [ "Average" ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [ "Average" ]
      }
     ]
    },
    {
     "title": "实例维度的请求平均延时",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 4 },
     "format": "ms",
     "valueName": "current",
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "InstanceRt",
       "period": "60",
       "project": "acs_slb_dashboard",
       "target": [ "Average" ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [ "Average" ]
      }
     ]
    },
    {
     "title": "实例维度4xx状态码",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 4 },
     "format": "cps",
     "valueName": "current",
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "InstanceStatusCode4xx",
       "period": "60",
       "project": "acs_slb_dashboard",
       "target": [ "Average" ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [ "Average" ]
      }
     ]
    },
    {
     "title": "实例维度5xx状态码",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 4 },
     "format": "cps",
     "valueName": "current",
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "InstanceStatusCode5xx",
       "period": "60",
       "project": "acs_slb_dashboard",
       "target": [ "Average" ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [ "Average" ]
      }
     ]
    },
    {
     "title": "QPS使用率",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "InstanceQpsUtilization",
       "period": "60",
       "project": "acs_slb_dashboard",
       "target": [ "Average" ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [ "Average" ]
      }
     ]
    },
    {
     "title": "实例维度的QPS",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
     "format": "cps",
     "valueName": "current",
     "targets": [
      {
       "dimensions": [ "$dimension" ],
       "metric": "InstanceQps",
       "period": "60",
       "project": "acs_slb_dashboard",
       "target": [ "Average" ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [ "Average" ]
      }
     ]
    }
   ]
  }
 ]
}