{
 "title": "RDS 监控",
 "tags": [
  "RDS",
  "阿里云"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "name", "label": "实例名称", "query": "rds" },
   { "name": "id", "query": "rds($name)" }
  ]
 },
 "panels": [
  { "title": "概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "name" },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "CpuUsage",
     "period": "60",
     "project": "acs_rds_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "MemoryUsage",
     "period": "60",
     "project": "acs_rds_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "DiskUsage",
     "period": "60",
     "project": "acs_rds_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "IOPSUsage",
     "period": "60",
     "project": "acs_rds_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "ConnectionUsage",
     "period": "60",
     "project": "acs_rds_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 9 },
   "content": "### [RDS 控制台](https://rds.console.aliyun.com/)"
  },
  { "title": "基础监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }, "repeat": "name" },
  {
   "title": "CPU使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "CpuUsage",
     "period": "60",
     "project": "acs_rds_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "MemoryUsage",
     "period": "60",
     "project": "acs_rds_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "DiskUsage",
     "period": "60",
     "project": "acs_rds_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "连接数使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "ConnectionUsage",
     "period": "60",
     "project": "acs_rds_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "IOPS使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "dimensions": [ "$id" ],
     "metric": "IOPSUsage",
     "period": "60",
     "project": "acs_rds_dashboard",
     "target": [ "Average" ],
     "type": "timeserie",
     "xcol": "timestamp",
     "ycol": [ "Average" ]
    }
   ]
  },
  {
   "title": "网络监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "repeat": "dimension",
   "collapsed": true,
   "panels": [
    {
     "title": "Mysql每秒网络入流量",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "dimensions": [ "$id" ],
       "metric": "MySQL_NetworkInNew",
       "period": "60",
       "project": "acs_rds_dashboard",
       "target": [ "Average" ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [ "Average" ]
      }
     ]
    },
    {
     "title": "Mysql每秒网络出流量",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "dimensions": [ "$id" ],
       "metric": "MySQL_NetworkOutNew",
       "period": "60",
       "project": "acs_rds_dashboard",
       "target": [ "Average" ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [ "Average" ]
      }
     ]
    },
    {
     "title": "Mysql当前活跃Sessions数",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": [ "$id" ],
       "metric": "MySQL_ActiveSessions",
       "period": "60",
       "project": "acs_rds_dashboard",
       "target": [ "Average" ],
       "type": "timeserie",
       "xcol": "timestamp",
       "ycol": [ "Average" ]
      }
     ]
    }
   ]
  },
  {
   "type": "yesoreyeram-boomtheme-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 37 },
   "targets": [
    { "project": "acs_ecs_dashboard", "type": "timeserie", "xcol": "timestamp" }
   ]
  }
 ]
}